// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARokekz8kQYeOUZsvkFAod73sk0aA7nHs',
    appId: '1:528080756464:web:816bc8850f39f86e196c35',
    messagingSenderId: '528080756464',
    projectId: 'prueba2-4ecbc',
    authDomain: 'prueba2-4ecbc.firebaseapp.com',
    databaseURL: 'https://prueba2-4ecbc-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-4ecbc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDinmTeY0sUV3QvWdkEQkitFWr9shWYUtg',
    appId: '1:528080756464:android:a2da82a2b558bad6196c35',
    messagingSenderId: '528080756464',
    projectId: 'prueba2-4ecbc',
    databaseURL: 'https://prueba2-4ecbc-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-4ecbc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARokekz8kQYeOUZsvkFAod73sk0aA7nHs',
    appId: '1:528080756464:web:09530c8de1053ee8196c35',
    messagingSenderId: '528080756464',
    projectId: 'prueba2-4ecbc',
    authDomain: 'prueba2-4ecbc.firebaseapp.com',
    databaseURL: 'https://prueba2-4ecbc-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-4ecbc.firebasestorage.app',
  );
}
